services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=notesql
    volumes:
      - notesql_pg:/bitnami/postgresql

volumes:
  notesql_pg:
