type Note {
  id: ID!
  author: User!
  title: String!
  body: String!
  priority: Boolean!
  status: Status!
  deleted_at: DateTime
  created_at: DateTime!
}

input NoteInput {
  body: String!
  title: String!
  authorId: ID!
}

enum Status {
  FINISHED
  UNFINISHED
}

type Query {
  getNotesByAuthor: [Note]!
}

type Mutation {
  writeNote(note: NoteInput!): Note!
  prioritizeNote(id: ID!, priority: Boolean!): Note!
  updateStatus(id: ID!, status: Status!): Note!
  deleteNote(id: ID!): Boolean!
}

scalar DateTime
