type User {
  id: ID!
  name: String!
  email: String!
  password: String!
  avatar_url: String
  created_at: DateTime!
}

input UserInput {
  name: String!
  email: String!
  password: String!
}

type Query {
  getUsers: [User!]!
  authenticateUser(email: String!, password: String!): User
}

type Mutation {
  createUser(data: UserInput!): User
}

scalar DateTime
